version: "3"

services:

  Vikram-demo-webapp:
    image: vikramsvk/spring-docker-demo
    networks:
      - vikram-network
    ports:
      - 80:8080
    depends_on:
      - database

  database:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - vikram-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vikram

networks:
  vikram-network:
